Google Analytics Integated
vinnovateit/VinHack-Website pull request #6
Opened 2019-03-14 12:58 UTC by ArpitKotecha

Change google tag id (UA-136271091-1) with the id from the account you want the insights on or comment your email so I can add your account to the existing tag.

2019-03-14 13:04 UTC, vinitshahdeo commented
That's awesome @ArpitKotecha !
Once I'll get the credentials from @ShreyaAnand, I'll update `Google Analytics ID` and merge this.

Can you update the same for [vinnovateit.com](https://vinnovateit.com/) too!

2019-03-14 13:06 UTC, vinitshahdeo requested changes
@ArpitKotecha, **add the script at end!**

Running `javascript` first may potentially cause performance issues. It's thumb rule, always load the JS after the DOM has loaded.

2019-03-14 13:12 UTC, ArpitKotecha commented
That's right but the analytics script is loaded asynchronously thus the browser makes a concurrent request for other assets. Also, Google recommends to put it right after head section so that it can track even when the user doesn't let the page finish loading

2019-03-14 13:13 UTC, ArpitKotecha commented
> That's awesome @ArpitKotecha !
> Once I'll get the credentials from @ShreyaAnand, I'll update `Google Analytics ID` and merge this.
> 
> Can you update the same for [vinnovateit.com](https://vinnovateit.com/) too!

Yes

2019-03-14 13:24 UTC, vinitshahdeo commented
> > @ArpitKotecha, **add the script at end!**
> > Running `javascript` first may potentially cause performance issues. It's thumb rule, always load the JS after the DOM has loaded.
> 
> That's right but the analytics script is loaded asynchronously thus the browser makes a concurrent request for other assets. Also, Google recommends to put it right after head section so that it can track even when the user doesn't let the page finish loading.
> But if needed I can put it at the end of head or body tag.

I agree now **Google** has provided async support so that we get **accurate number of clicks** to our page. This might not cause any kind of performance issues util we don't have much client side rendering of components.

But the point here is we want users to spend some time on our website. Just by clicking and leaving the website even before `<body></body>` has loaded doesn't add any value to our use case. We want to track visitors who're interested in our own Hack - [VinHack](https://vinhack.vinnovateit.com/)!

This is my concern!

2019-03-14 13:34 UTC, vinitshahdeo commented on index.html
> +	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-136271091-1"></script>
```suggestion
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXX"></script>
```

2019-03-14 13:35 UTC, vinitshahdeo commented on index.html
> +		gtag('config', 'UA-136271091-1');
```suggestion
		gtag('config', 'UA-XXXXXXX');
```

2019-03-14 13:44 UTC, ArpitKotecha commented
> > > @ArpitKotecha, **add the script at end!**
> > > Running `javascript` first may potentially cause performance issues. It's thumb rule, always load the JS after the DOM has loaded.
> > 
> > 
> > That's right but the analytics script is loaded asynchronously thus the browser makes a concurrent request for other assets. Also, Google recommends to put it right after head section so that it can track even when the user doesn't let the page finish loading.
> > But if needed I can put it at the end of head or body tag.
> 
> I agree now **Google** has provided async support so that we get **accurate number of clicks** to our page. This might not cause any kind of performance issues util we don't have much client side rendering of components.
> 
> But the point here is we want users to spend some time on our website. Just by clicking and leaving the website even before `<body></body>` has loaded doesn't add any value to our use case. We want to track visitors who're interested in our own Hack - [VinHack](https://vinhack.vinnovateit.com/)!
> 
> This is my concern!

Well, in this case as I've made the requested changes. Although if we put Google Analytics script right after head tag we can know how many users are leaving because of website load time I guess we can use that in [Vinnovate](www.vinnovateit.com) website.

2019-03-17 15:25 UTC, ArpitKotecha commented
Please ask @ShreyaAnand for google analytics credentials for [vinhack ](http://vinhack.vinnovateit.com)and [vinnovative ](http://vinnovateit.com)website

2019-03-17 15:28 UTC, vinitshahdeo commented
> Please ask @ShreyaAnand didi for google analytics credentials for [vinhack ](http://vinhack.vinnovateit.com)and [vinnovative ](http://vinnovateit.com)website

Sure, I'll do!

2019-03-17 15:35 UTC, vinitshahdeo commented on index.html
> +		gtag('config', 'UA-XXXXXXXXX-X');
gtag('config', 'UA-136415898-1');

Use this `tracking ID`.

2019-03-17 15:35 UTC, ShreyaAnand commented
Sent to @vinitshahdeo .

2019-03-17 15:36 UTC, vinitshahdeo commented
`UA-136415898-1`

**Use this tracking ID!**

@ArpitKotecha 💯

2019-03-17 15:51 UTC, vinitshahdeo commented
Can you resolve the conflicts? 

**Pull the latest `master` branch** and make the changes!

@ArpitKotecha

2019-03-17 15:52 UTC, vinitshahdeo reviewed
**Please resolve the conflicts!**

2019-03-17 15:56 UTC, ArpitKotecha commented
> **Please resolve the conflicts!**

Sure. I'll resolve them.

2019-03-17 16:03 UTC, ArpitKotecha commented
> > **Please resolve the conflicts!**
> 
> Sure. I'll resolve them.

Conflicts resolved @vinitshahdeo

2019-03-17 16:09 UTC, vinitshahdeo approved these changes
I'm merging it!
Good work @ArpitKotecha !

2019-03-17 16:10 UTC, merged